[project]
name = "cosmos-reason1"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["decord", "qwen_vl_utils", "transformers", "vllm"]

[project.optional-dependencies]
# https://github.com/QwenLM/Qwen2.5-VL/tree/main/qwen-vl-finetune#requirements
train = [
    "datasets",
    "torch==2.6.0",
    "torchvision==0.21.0",
    "transformers==4.50.0",
    "deepspeed==0.16.4",
    "flash_attn==2.7.4.post1",
    "accelerate==1.4.0",
    "torchcodec==0.2",
    "wandb",
]

[dependency-groups]
# https://github.com/Dao-AILab/flash-attention?tab=readme-ov-file#installation-and-features
build = ["ninja", "packaging", "pip>=25.1", "psutil", "torch"]
compile = ["flash-attn"]

[tool.uv]
no-build-isolation-package = ["flash-attn"]

[tool.deptry]
known_first_party = ["tools"]

[tool.deptry.package_module_name_map]
ffmpeg-python = "ffmpeg"
opencv-python = "cv2"

[tool.deptry.per_rule_ignores]
DEP002 = ["wandb"]
